vich_uploader:
    db_driver: orm

    mappings:
        photo_profil:
            uri_prefix: /images/participants
            upload_destination: '%kernel.project_dir%/public/images/participants'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
